---
- hosts: forgejo
  become: yes

  handlers:
  - name: Reload Caddy
    service:
      name: caddy
      state: reloaded
    delegate_to: "{{ item }}"
    loop: "{{ groups['caddy'] }}"

  - name: Restart Forgejo
    service:
      name: forgejo
      state: restarted

  tasks:
  - name: Install Forgejo
    package:
      name: forgejo
      state: latest

  - name: Copy configuration
    template:
      src: ./files/app.j2.ini
      dest: /etc/forgejo/app.ini
      owner: forgejo
      group: www-data # Alpine packaging choice
      mode: "0640"
    tags: config
    notify: Restart Forgejo

  - name: Copy Caddy config
    template:
      src: ./files/Caddyfile.j2
      dest: /etc/caddy/conf.d/{{ forgejo.domain }}.conf
      owner: caddy
      group: caddy
      mode: "0640"
    notify: Reload Caddy
    delegate_to: "{{ item }}"
    loop: "{{ groups['caddy'] }}"
    tags: config

  - name: Start and enable Forgejo service
    service:
      name: forgejo
      state: started
      enabled: true
